/**
 * Item ID ↔ name bidirectional lookup.
 *
 * Some SFL endpoints (especially JWT-authenticated ones like
 * `/data?type=session`) return inventory keyed by numeric token IDs rather
 * than human-readable names. The name→ID mapping lives in
 * `src/data/marketplace_items.json` (generated by
 * `scripts/update-marketplace.mjs` from the SFL GitHub source).
 *
 * This module builds a reverse map once at module load so we can translate
 * numeric keys on the fly in the SFL client's `normalize()` step.
 */

import marketplaceData from "@/data/marketplace_items.json";

interface MarketplaceItem {
  id: number;
  name: string;
  category: string;
  type: string;
}

const ITEMS = (marketplaceData.items as MarketplaceItem[]) ?? [];

// id -> name (stable: first-write wins so placeholder entries don't clobber).
const ID_TO_NAME = new Map<number, string>();
// name -> id for the reverse direction (handy for API callers).
const NAME_TO_ID = new Map<string, number>();

for (const item of ITEMS) {
  if (item.id > 0 && !ID_TO_NAME.has(item.id)) {
    ID_TO_NAME.set(item.id, item.name);
  }
  if (item.name && !NAME_TO_ID.has(item.name)) {
    NAME_TO_ID.set(item.name, item.id);
  }
}

/** Resolves a numeric ID (or numeric string) to the in-game item name. */
export function resolveItemName(id: number | string): string | null {
  const n = typeof id === "number" ? id : parseInt(id, 10);
  if (!Number.isFinite(n)) return null;
  return ID_TO_NAME.get(n) ?? null;
}

/** Resolves an item name to its numeric token ID. Returns 0 if unknown. */
export function resolveItemId(name: string): number {
  return NAME_TO_ID.get(name) ?? 0;
}

/**
 * Translates an inventory map whose keys MAY be numeric IDs or names into a
 * normalized `{ name: quantity }` shape. Unknown numeric IDs are preserved
 * under a readable `"Unknown #12345"` label so Master can spot missing
 * mappings instead of dropping data silently.
 */
export function normalizeInventoryKeys(
  raw: Record<string, string | number>,
): Record<string, number> {
  const out: Record<string, number> = {};
  for (const [k, v] of Object.entries(raw)) {
    const qty = typeof v === "number" ? v : parseFloat(v);
    if (!Number.isFinite(qty)) continue;
    const isNumericKey = /^\d+$/.test(k);
    if (isNumericKey) {
      const name = resolveItemName(k);
      out[name ?? `Unknown #${k}`] = qty;
    } else {
      out[k] = qty;
    }
  }
  return out;
}

/** Debug helper: returns the total number of mappings loaded. */
export function getLookupStats(): { idToName: number; nameToId: number } {
  return { idToName: ID_TO_NAME.size, nameToId: NAME_TO_ID.size };
}
